# Generated by Django 3.1.7 on 2021-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(help_text='Nombre del equipo participante', max_length=80, verbose_name='Nombre Equipo')),
                ('logo_equipo', models.ImageField(blank=True, help_text='Logo del equipo', null=True, upload_to='logos_equipos', verbose_name='Logo / Imagen')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(help_text='Apellido del jugador', max_length=80, verbose_name='Apellido')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del jugador', max_length=80, null=True, verbose_name='Nombre')),
                ('numero', models.PositiveIntegerField(blank=True, default=0, help_text='Numero de camiseta del jugador', null=True, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
