# Generated by Django 3.1.7 on 2021-03-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_jugador_id_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='id_equipo',
            field=models.ForeignKey(default=None, help_text='Nombre del equipo', on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Equipo'),
        ),
    ]
