# Generated by Django 3.1.7 on 2021-04-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_auto_20210407_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Numero de camiseta del jugador', null=True, verbose_name='Numero'),
        ),
    ]
