# Generated by Django 3.1.7 on 2021-03-18 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_auto_20210317_2330'),
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AddField(
            model_name='campeonato',
            name='descripcion',
            field=models.TextField(default='', help_text='Descripcion', max_length=250, verbose_name='Descripcion del campeonato'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha en la que inició el campeonato', null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='id_equipo',
            field=models.ForeignKey(default=0, help_text='Nombre del equipo', on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Id_delequipo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='nombre_campeonato',
            field=models.CharField(default='', help_text='Nombre del campeonato', max_length=80, verbose_name='Nombre Campeonato'),
        ),
    ]
