# Generated by Django 3.1.7 on 2021-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_auto_20210317_2330'),
        ('campeonato', '0003_auto_20210318_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='id_equipo',
            field=models.ForeignKey(blank=True, default=0, help_text='Nombre del equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Id_delequipo'),
        ),
    ]
