# Generated by Django 3.1.7 on 2021-03-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
        ('equipo', '0002_auto_20210317_2330'),
        ('partido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuentro',
            options={'verbose_name': 'Encuentro', 'verbose_name_plural': 'Encuentros'},
        ),
        migrations.AlterModelOptions(
            name='goles',
            options={'verbose_name': 'Gol', 'verbose_name_plural': 'Goles'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AddField(
            model_name='encuentro',
            name='estado',
            field=models.CharField(choices=[('P', 'Por Jugar'), ('J', 'Jugado'), ('S', 'Suspendido')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='fecha_encuentro',
            field=models.DateField(blank=True, help_text='Fecha en la que se jugó el partido', null=True, verbose_name='Fecha del Encuentro'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='id_campeonato',
            field=models.ForeignKey(default=0, help_text='Nombre del campeonato que se está jugando', on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato', verbose_name='Campeonato'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='id_equipo1',
            field=models.ForeignKey(default=0, help_text='Datos del equipo que jugó el partido', on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='equipo.equipo', verbose_name='Equipo N°1'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='id_equipo2',
            field=models.ForeignKey(default=0, help_text='Datos del equipo que jugó el partido', on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='equipo.equipo', verbose_name='Equipo N°2'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='id_sede',
            field=models.ForeignKey(default='', help_text='Sede en la que se jugó el encuentro', on_delete=django.db.models.deletion.CASCADE, to='partido.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='goles',
            name='id_jugador',
            field=models.ForeignKey(default=0, help_text='Jugador', on_delete=django.db.models.deletion.CASCADE, to='equipo.jugador', verbose_name='Gol anotado por el jugador'),
        ),
        migrations.AddField(
            model_name='goles',
            name='id_partido',
            field=models.ForeignKey(default=0, help_text='Partido donde se convirtio el gol', on_delete=django.db.models.deletion.CASCADE, to='partido.partido', verbose_name='Partido'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_eq1',
            field=models.PositiveIntegerField(default=0, help_text='Goles del equipo 1', verbose_name='Goles Equipo 1'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_eq2',
            field=models.PositiveIntegerField(default=0, help_text='Goles del equipo 2', verbose_name='Goles Equipo 2'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_encuentro',
            field=models.ForeignKey(default=0, help_text='Datos del encuentro', on_delete=django.db.models.deletion.CASCADE, to='partido.encuentro', verbose_name='Encuentro'),
        ),
        migrations.AddField(
            model_name='sede',
            name='nombre_sede',
            field=models.CharField(default='', help_text='Sede donde se juega el partido', max_length=80, verbose_name='Nombre Sede'),
        ),
    ]
